name: Python application

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ main ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "dapurspl" --password-stdin
        docker image build -t us-east1-docker.pkg.dev/qwiklabs-gcp-04-46330666a515/proz/mod:1 .
        docker push us-east1-docker.pkg.dev/qwiklabs-gcp-04-46330666a515/proz/mod:1
